In [1]:
import numpy as np
import pandas as pd
import keras
import warnings
import import_ipynb
import Pipeline_Latest as pp2
import DeepBind_Latest as db22
import os
import sys
import matplotlib.pyplot as pl
import subprocess
warnings.filterwarnings("ignore")

dir(db22)

/home/abhinav/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


importing Jupyter notebook from Pipeline_Latest.ipynb
importing Jupyter notebook from DeepBind_Latest.ipynb


['__builtins__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 'deepbind1',
 'get_ipython',
 'import_ipynb',
 'json',
 'keras',
 'np',
 'one_hot_encode',
 'pd',
 'pp2',
 'warnings']

In [2]:
filenames1 = ['ENCFF127XXD_H3K4me3.bed','ENCFF099LMD_H3K4me2.bed', 'ENCFF139CKE_H4K20me1.bed', 'ENCFF183UQD_H3K4me1.bed','ENCFF322IFF_H3K27me3.bed', 'ENCFF379CMJ_EP300.bed', 'ENCFF498CMP_H3K36me3.bed', 'ENCFF578UBP_H3K27ac.bed', 'ENCFF624XRN_H2AFZ.bed', 'ENCFF737AMS_H3K4me3.bed', 'ENCFF894VEM_H3K9me3.bed']


In [3]:
filenames2 = ['ENCFF127XXD_H3K4me3.bed','ENCFF099LMD_H3K4me2.bed', 'ENCFF139CKE_H4K20me1.bed', 'ENCFF183UQD_H3K4me1.bed','ENCFF322IFF_H3K27me3.bed', 'ENCFF379CMJ_EP300.bed', 'ENCFF498CMP_H3K36me3.bed', 'ENCFF578UBP_H3K27ac.bed', 'ENCFF624XRN_H2AFZ.bed', 'ENCFF737AMS_H3K4me3.bed', 'ENCFF894VEM_H3K9me3.bed']


In [4]:
df_final = pd.DataFrame(columns=['File1','File2','Accuracy'])

print len(filenames1)
print len(filenames2)


11
11


In [6]:
from Bio import SeqIO
count=0
for i in range(len(filenames1)-1):
    for j in range(i+1,len(filenames2)):
        f1 = filenames1[i]
        f2 = filenames2[j]
        num_intersections_in30, num_in_class0, num_in_class1= pp2.pipe(f1,f2)
        
        file1, file_extension1 = os.path.splitext(f1)
        file2, file_extension2 = os.path.splitext(f2)
        
        class0_train= "inter_fa/"+file1+"_70"+".fa"
        class1_train= "inter_fa/"+file2+"_70"+".fa"
        class0_test= "inter_fa/"+file1+"_30"+".fa"
        class1_test= "inter_fa/"+file2+"_30"+".fa"
               

        list0=[]
        list1=[]

        #making dataframe for train data
        for record in SeqIO.parse(class0_train, "fasta"):
            list0.append(str(record.seq))
        for record in SeqIO.parse(class1_train, "fasta"):
            list1.append(str(record.seq))
        target=[]
    
    
        for t in range(len(list0)):
            target.append(0)
        
        for m in range(len(list1)):
            target.append(1)
        
        sequences=list0+list1

        dict = {'seq': sequences, 'target': target}
        df_train = pd.DataFrame(dict)
        
        
        #making dataframe for test data
        list0_test=[]
        list1_test=[]

        for record in SeqIO.parse(class0_test, "fasta"):
            list0_test.append(str(record.seq))
        for record in SeqIO.parse(class1_test, "fasta"):
            list1_test.append(str(record.seq))
        target=[]
    
    
        for t in range(len(list0_test)):
            target.append(0)
        
        for m in range(len(list1_test)):
            target.append(1)
        
        sequences1=list0_test+list1_test

        dict1 = {'seq': sequences1, 'target': target}
        df_test = pd.DataFrame(dict1)
        
        print(df_train.shape)
        print(df_test.shape)
        
        
        #calling deepbind
        accuracy,scores= db22.deepbind1(df_train,df_test,count)
        print("Num intersections in 30%: ",num_intersections_in30,"\n")
        print("Num in class0: ",num_in_class0,"\n")
        print("Num in class1: ",num_in_class1,"\n")
        print("File1: ",f1,"\n")
        print("File2: ",f2,"\n")
        print("Accuracy: ",accuracy,"\n")
        print("Prob: ",scores,"\n")
        #print("Probability: ",scores,"\n")
        df_final.loc[count,['File1']] = str(f1)
        df_final.loc[count, ['File2']] = str(f2)
        print accuracy
        df_final.loc[count, ['Accuracy']] = accuracy
        
        
        #histogram stuff
        title1="Class0 num: "+str(num_in_class0)+" Class1 num: "+str(num_in_class1)+" Num. of 30% intersections: "+str(num_intersections_in30)
        plot_title= "histograms/"+file1+"_"+file2+".png"
        pl.figure(figsize=(7,7))
#         n,bins,patches = pl.hist(scores,bins=10, density = False, edgecolor='black')
#         for p in patches:
#             pl.text(p.get_x() + p.get_width()/2., p.get_height(), '%d' % int(p.get_height()),fontsize=12, color='red', ha='center', va='bottom')
#         pl.title(title1)
#         pl.xlabel("Predicted probabilities")
#         pl.ylabel("Frequency")
        n1,bins1,patches1 = pl.hist(scores[0:num_in_class0],bins=10, density = False, edgecolor='black',alpha=0.5,label = "class0-red")
        n2,bins2,patches2 = pl.hist(scores[num_in_class0+1:],bins=10, density = False, edgecolor='black',alpha=0.5, label = "class1-black")
        for p in patches1:
            pl.text(p.get_x() + p.get_width()/2., p.get_height(), '%d' % int(p.get_height()),fontsize=12, color='red', ha='center', va='bottom')
        for p in patches2:
            pl.text(p.get_x() + p.get_width()/2., p.get_height(), '%d' % int(p.get_height()),fontsize=12, color='black', ha='center', va='bottom')
        pl.title(title1)
        pl.xlabel("Predicted probabilities")
        pl.ylabel("Frequency")
        pl.legend(loc='upper left')
        pl.savefig(plot_title)
        pl.clf()
        
        count=count+1

8333
(37158, 2)
(33033, 2)
('Shape is: ', (37158, 2))
[[[0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[1. 0. 0. 0.]
  [0. 0. 0. 1.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]]

 ...

 [[0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [1. 0. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]]]
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_4 (Conv1D)            (None, 181, 10)           810       
Total params: 810
Trainable params: 810
Non-trainable params: 0
______________________________________________________

53348/53348 [==============================] - 9s 166us/step - loss: 0.5408 - acc: 0.7203
Epoch 4/5
53348/53348 [==============================] - 9s 165us/step - loss: 0.5319 - acc: 0.7276
Epoch 5/5
53348/53348 [==============================] - 9s 164us/step - loss: 0.5243 - acc: 0.7330
[[[0. 0. 0. 1.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [1. 0. 0. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]]

 [[1. 0. 0. 0.]
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 ...

 [[1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 1. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]]]
23818/23818 [==============================] - 1s 52us/step
[[0.29764193]
 [0.28

('Num intersections in 30%: ', 3613, '\n')
('Num in class0: ', 13416, '\n')
('Num in class1: ', 34142, '\n')
('File1: ', 'ENCFF127XXD_H3K4me3.bed', '\n')
('File2: ', 'ENCFF183UQD_H3K4me1.bed', '\n')
('Accuracy: ', 0.7613970376082324, '\n')
('Prob: ', array([[0.37766   ],
       [0.3237612 ],
       [0.6025618 ],
       ...,
       [0.7886165 ],
       [0.87007564],
       [0.8476078 ]], dtype=float32), '\n')
0.7613970376082324
70
(82834, 2)
(35640, 2)
('Shape is: ', (82834, 2))
[[[0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]]

 [[0. 0. 1. 0.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  ...
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]]

 ...

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]]

 [[0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 

Epoch 1/5
149228/149228 [==============================] - 25s 169us/step - loss: 0.3789 - acc: 0.8573
Epoch 2/5
149228/149228 [==============================] - 24s 164us/step - loss: 0.3636 - acc: 0.8581
Epoch 3/5
149228/149228 [==============================] - 25s 167us/step - loss: 0.3560 - acc: 0.8598
Epoch 4/5
149228/149228 [==============================] - 25s 168us/step - loss: 0.3503 - acc: 0.8619
Epoch 5/5
149228/149228 [==============================] - 25s 167us/step - loss: 0.3448 - acc: 0.8638
[[[0. 0. 0. 1.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [1. 0. 0. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]]

 [[1. 0. 0. 0.]
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 ...

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]]

 [[0. 0. 0. 1.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 0. 

('Num intersections in 30%: ', 446, '\n')
('Num in class0: ', 13416, '\n')
('Num in class1: ', 27926, '\n')
('File1: ', 'ENCFF127XXD_H3K4me3.bed', '\n')
('File2: ', 'ENCFF498CMP_H3K36me3.bed', '\n')
('Accuracy: ', 0.7801324498308866, '\n')
('Prob: ', array([[0.7543704 ],
       [0.3741249 ],
       [0.2579821 ],
       ...,
       [0.79932106],
       [0.48349437],
       [0.65974295]], dtype=float32), '\n')
0.7801324498308866
630
(72211, 2)
(43871, 2)
('Shape is: ', (72211, 2))
[[[0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 ...

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 0. 1.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1.

Epoch 1/5
66559/66559 [==============================] - 12s 175us/step - loss: 0.5275 - acc: 0.7756
Epoch 2/5
66559/66559 [==============================] - 11s 167us/step - loss: 0.5183 - acc: 0.7759
Epoch 3/5
66559/66559 [==============================] - 11s 167us/step - loss: 0.5138 - acc: 0.7757
Epoch 4/5
66559/66559 [==============================] - 11s 171us/step - loss: 0.5066 - acc: 0.7767
Epoch 5/5
66559/66559 [==============================] - 11s 170us/step - loss: 0.4976 - acc: 0.7781
[[[0. 0. 0. 1.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [1. 0. 0. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]]

 [[1. 0. 0. 0.]
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 ...

 [[0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [

('Num intersections in 30%: ', 3438, '\n')
('Num in class0: ', 13416, '\n')
('Num in class1: ', 6434, '\n')
('File1: ', 'ENCFF127XXD_H3K4me3.bed', '\n')
('File2: ', 'ENCFF737AMS_H3K4me3.bed', '\n')
('Accuracy: ', 0.7512508030719331, '\n')
('Prob: ', array([[0.066687  ],
       [0.06531572],
       [0.03139323],
       ...,
       [0.2450052 ],
       [0.05252551],
       [0.54887074]], dtype=float32), '\n')
0.7512508030719331
21
(35275, 2)
(15183, 2)
('Shape is: ', (35275, 2))
[[[0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]]

 [[0. 0. 1. 0.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  ...
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]]

 ...

 [[0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0

Epoch 1/5
66256/66256 [==============================] - 12s 182us/step - loss: 0.6093 - acc: 0.6752
Epoch 2/5
66256/66256 [==============================] - 11s 170us/step - loss: 0.5745 - acc: 0.6960
Epoch 3/5
66256/66256 [==============================] - 11s 170us/step - loss: 0.5673 - acc: 0.7003
Epoch 4/5
66256/66256 [==============================] - 11s 166us/step - loss: 0.5622 - acc: 0.7036
Epoch 5/5
66256/66256 [==============================] - 11s 164us/step - loss: 0.5565 - acc: 0.7063
[[[1. 0. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  ...
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 0. 0. 1.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]]

 [[0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 ...

 [[1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 1. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 1. 0.]
  [

('Num intersections in 30%: ', 6977, '\n')
('Num in class0: ', 19617, '\n')
('Num in class1: ', 34142, '\n')
('File1: ', 'ENCFF099LMD_H3K4me2.bed', '\n')
('File2: ', 'ENCFF183UQD_H3K4me1.bed', '\n')
('Accuracy: ', 0.6899851773673689, '\n')
('Prob: ', array([[0.7066509 ],
       [0.56231785],
       [0.75324935],
       ...,
       [0.7900502 ],
       [0.90635604],
       [0.86416894]], dtype=float32), '\n')
0.6899851773673689
231
(96764, 2)
(41841, 2)
('Shape is: ', (96764, 2))
[[[0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 ...

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]]

 [[0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0.

Epoch 1/5
152947/152947 [==============================] - 27s 178us/step - loss: 0.4466 - acc: 0.8013
Epoch 2/5
152947/152947 [==============================] - 26s 171us/step - loss: 0.4298 - acc: 0.8054
Epoch 3/5
152947/152947 [==============================] - 26s 172us/step - loss: 0.4218 - acc: 0.8074
Epoch 4/5
152947/152947 [==============================] - 27s 174us/step - loss: 0.4164 - acc: 0.8092
Epoch 5/5
152947/152947 [==============================] - 26s 172us/step - loss: 0.4101 - acc: 0.8116
[[[1. 0. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  ...
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 0. 0. 1.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]]

 [[0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 ...

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]]

 [[0. 0. 0. 1.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 0. 

('Num intersections in 30%: ', 718, '\n')
('Num in class0: ', 19617, '\n')
('Num in class1: ', 27926, '\n')
('File1: ', 'ENCFF099LMD_H3K4me2.bed', '\n')
('File2: ', 'ENCFF498CMP_H3K36me3.bed', '\n')
('Accuracy: ', 0.7921001254084472, '\n')
('Prob: ', array([[0.1785338 ],
       [0.28838745],
       [0.31195197],
       ...,
       [0.71293676],
       [0.5822202 ],
       [0.48512474]], dtype=float32), '\n')
0.7921001254084472
1142
(76553, 2)
(50072, 2)
('Shape is: ', (76553, 2))
[[[0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 ...

 [[0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [1. 0

Epoch 1/5
69330/69330 [==============================] - 13s 185us/step - loss: 0.6325 - acc: 0.6598
Epoch 2/5
69330/69330 [==============================] - 12s 176us/step - loss: 0.6190 - acc: 0.6630
Epoch 3/5
69330/69330 [==============================] - 12s 177us/step - loss: 0.6116 - acc: 0.6685
Epoch 4/5
69330/69330 [==============================] - 12s 174us/step - loss: 0.6045 - acc: 0.6755
Epoch 5/5
69330/69330 [==============================] - 12s 171us/step - loss: 0.5950 - acc: 0.6842
[[[1. 0. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  ...
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 0. 0. 1.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]]

 [[0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 ...

 [[0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [

('Num intersections in 30%: ', 3237, '\n')
('Num in class0: ', 19617, '\n')
('Num in class1: ', 6434, '\n')
('File1: ', 'ENCFF099LMD_H3K4me2.bed', '\n')
('File2: ', 'ENCFF737AMS_H3K4me3.bed', '\n')
('Accuracy: ', 0.8009171008714934, '\n')
('Prob: ', array([[0.101292  ],
       [0.01692662],
       [0.03470474],
       ...,
       [0.2282074 ],
       [0.43627733],
       [0.824519  ]], dtype=float32), '\n')
0.8009171008714934
34
(49745, 2)
(21384, 2)
('Shape is: ', (49745, 2))
[[[0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 ...

 [[0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0

Epoch 1/5
96014/96014 [==============================] - 18s 185us/step - loss: 0.4787 - acc: 0.7908
Epoch 2/5
96014/96014 [==============================] - 17s 178us/step - loss: 0.4722 - acc: 0.7931
Epoch 3/5
96014/96014 [==============================] - 17s 177us/step - loss: 0.4685 - acc: 0.7941
Epoch 4/5
96014/96014 [==============================] - 17s 177us/step - loss: 0.4661 - acc: 0.7946
Epoch 5/5
96014/96014 [==============================] - 17s 177us/step - loss: 0.4633 - acc: 0.7962
[[[0. 0. 1. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]]

 [[0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]
  ...
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]]

 ...

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 0. 0. 1.]
  [

('Num intersections in 30%: ', 906, '\n')
('Num in class0: ', 10402, '\n')
('Num in class1: ', 22224, '\n')
('File1: ', 'ENCFF139CKE_H4K20me1.bed', '\n')
('File2: ', 'ENCFF322IFF_H3K27me3.bed', '\n')
('Accuracy: ', 0.6224248882815773, '\n')
('Prob: ', array([[0.65506536],
       [0.7746592 ],
       [0.74550456],
       ...,
       [0.7798485 ],
       [0.80926406],
       [0.8423654 ]], dtype=float32), '\n')
0.6224248882815773
209
(158336, 2)
(69556, 2)
('Shape is: ', (158336, 2))
[[[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]
  ...
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]

 [[0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 ...

 [[0. 0. 1. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]
  [1.

Epoch 1/5
84248/84248 [==============================] - 16s 189us/step - loss: 0.4399 - acc: 0.8088
Epoch 2/5
84248/84248 [==============================] - 15s 177us/step - loss: 0.4296 - acc: 0.8143
Epoch 3/5
84248/84248 [==============================] - 15s 179us/step - loss: 0.4266 - acc: 0.8173
Epoch 4/5
84248/84248 [==============================] - 15s 173us/step - loss: 0.4247 - acc: 0.8173
Epoch 5/5
84248/84248 [==============================] - 15s 177us/step - loss: 0.4214 - acc: 0.8203
[[[0. 0. 1. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]]

 [[0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]
  ...
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]]

 ...

 [[0. 0. 1. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]]

 [[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  ...
  [1. 0. 0. 0.]
  [

('Num intersections in 30%: ', 412, '\n')
('Num in class0: ', 10402, '\n')
('Num in class1: ', 30455, '\n')
('File1: ', 'ENCFF139CKE_H4K20me1.bed', '\n')
('File2: ', 'ENCFF578UBP_H3K27ac.bed', '\n')
('Accuracy: ', 0.5941940556687333, '\n')
('Prob: ', array([[0.78019935],
       [0.56339544],
       [0.66268647],
       ...,
       [0.7437167 ],
       [0.78057235],
       [0.39774272]], dtype=float32), '\n')
0.5941940556687333
130
(91683, 2)
(39578, 2)
('Shape is: ', (91683, 2))
[[[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]
  ...
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]

 [[0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 ...

 [[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [0. 0.

Epoch 1/5
38668/38668 [==============================] - 8s 208us/step - loss: 0.4427 - acc: 0.8060
Epoch 2/5
38668/38668 [==============================] - 7s 174us/step - loss: 0.3706 - acc: 0.8442
Epoch 3/5
38668/38668 [==============================] - 7s 177us/step - loss: 0.3586 - acc: 0.8491
Epoch 4/5
38668/38668 [==============================] - 7s 178us/step - loss: 0.3498 - acc: 0.8545
Epoch 5/5
38668/38668 [==============================] - 7s 180us/step - loss: 0.3434 - acc: 0.8575
[[[0. 0. 1. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]]

 [[0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]
  ...
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]]

 ...

 [[0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]
  ...
  [1. 0. 0. 0.]
  [0. 1.

('Num intersections in 30%: ', 4, '\n')
('Num in class0: ', 10402, '\n')
('Num in class1: ', 1767, '\n')
('File1: ', 'ENCFF139CKE_H4K20me1.bed', '\n')
('File2: ', 'ENCFF894VEM_H3K9me3.bed', '\n')
('Accuracy: ', 0.7412805447387409, '\n')
('Prob: ', array([[0.0616104 ],
       [0.18429129],
       [0.10086993],
       ...,
       [0.6402478 ],
       [0.21751752],
       [0.15559353]], dtype=float32), '\n')
0.7412805447387409
185
(130649, 2)
(56366, 2)
('Shape is: ', (130649, 2))
[[[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  ...
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 0. 1.]
  ...
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]]

 [[0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]]

 ...

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]]

 [[0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 

Epoch 1/5
182348/182348 [==============================] - 34s 189us/step - loss: 0.5666 - acc: 0.6839
Epoch 2/5
182348/182348 [==============================] - 33s 182us/step - loss: 0.5363 - acc: 0.7100
Epoch 3/5
182348/182348 [==============================] - 33s 182us/step - loss: 0.5231 - acc: 0.7203
Epoch 4/5
182348/182348 [==============================] - 33s 179us/step - loss: 0.5152 - acc: 0.7254
Epoch 5/5
182348/182348 [==============================] - 33s 182us/step - loss: 0.5089 - acc: 0.7300
[[[0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 0. 1.]
  [1. 0. 0. 0.]
  [0. 0. 0. 1.]
  ...
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 ...

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]]

 [[0. 0. 0. 1.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 0. 

('Num intersections in 30%: ', 2109, '\n')
('Num in class0: ', 34142, '\n')
('Num in class1: ', 27926, '\n')
('File1: ', 'ENCFF183UQD_H3K4me1.bed', '\n')
('File2: ', 'ENCFF498CMP_H3K36me3.bed', '\n')
('Accuracy: ', 0.6658528976383365, '\n')
('Prob: ', array([[0.5612131 ],
       [0.45235994],
       [0.5043745 ],
       ...,
       [0.40292594],
       [0.31432807],
       [0.3979211 ]], dtype=float32), '\n')
0.6658528976383365
2022
(115660, 2)
(64597, 2)
('Shape is: ', (115660, 2))
[[[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  ...
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 0. 1.]
  ...
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]]

 [[0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]]

 ...

 [[0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [1

Epoch 1/5
112141/112141 [==============================] - 22s 197us/step - loss: 0.6156 - acc: 0.6508
Epoch 2/5
112141/112141 [==============================] - 21s 184us/step - loss: 0.5886 - acc: 0.6778
Epoch 3/5
112141/112141 [==============================] - 21s 186us/step - loss: 0.5800 - acc: 0.6850
Epoch 4/5
112141/112141 [==============================] - 20s 181us/step - loss: 0.5737 - acc: 0.6911
Epoch 5/5
112141/112141 [==============================] - 21s 185us/step - loss: 0.5651 - acc: 0.6985
[[[0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 0. 1.]
  [1. 0. 0. 0.]
  [0. 0. 0. 1.]
  ...
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 ...

 [[0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 1. 

('Num intersections in 30%: ', 591, '\n')
('Num in class0: ', 34142, '\n')
('Num in class1: ', 6434, '\n')
('File1: ', 'ENCFF183UQD_H3K4me1.bed', '\n')
('File2: ', 'ENCFF737AMS_H3K4me3.bed', '\n')
('Accuracy: ', 0.8986847603711515, '\n')
('Prob: ', array([[0.02748313],
       [0.00994733],
       [0.01326386],
       ...,
       [0.82122076],
       [0.3499972 ],
       [0.9926528 ]], dtype=float32), '\n')
0.8986847603711515
87
(83342, 2)
(35909, 2)
('Shape is: ', (83342, 2))
[[[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  ...
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 0. 1.]
  ...
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]]

 [[0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]]

 ...

 [[0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0.

Epoch 1/5
188747/188747 [==============================] - 36s 192us/step - loss: 0.4917 - acc: 0.7573
Epoch 2/5
188747/188747 [==============================] - 34s 182us/step - loss: 0.4666 - acc: 0.7743
Epoch 3/5
188747/188747 [==============================] - 35s 184us/step - loss: 0.4512 - acc: 0.7821
Epoch 4/5
188747/188747 [==============================] - 34s 182us/step - loss: 0.4414 - acc: 0.7879
Epoch 5/5
188747/188747 [==============================] - 35s 185us/step - loss: 0.4332 - acc: 0.7927
[[[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]

 ...

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]]

 [[0. 0. 0. 1.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 0. 

('Num intersections in 30%: ', 3, '\n')
('Num in class0: ', 22224, '\n')
('Num in class1: ', 27926, '\n')
('File1: ', 'ENCFF322IFF_H3K27me3.bed', '\n')
('File2: ', 'ENCFF498CMP_H3K36me3.bed', '\n')
('Accuracy: ', 0.7933463692703338, '\n')
('Prob: ', array([[0.9166493 ],
       [0.6508266 ],
       [0.8542615 ],
       ...,
       [0.5629935 ],
       [0.23956615],
       [0.6609286 ]], dtype=float32), '\n')
0.7933463692703338
327
(122257, 2)
(52679, 2)
('Shape is: ', (122257, 2))
[[[1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  ...
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]

 ...

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 0. 1.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1

Epoch 1/5
118948/118948 [==============================] - 24s 204us/step - loss: 0.6227 - acc: 0.6412
Epoch 2/5
118948/118948 [==============================] - 22s 187us/step - loss: 0.5944 - acc: 0.6732
Epoch 3/5
118948/118948 [==============================] - 21s 180us/step - loss: 0.5872 - acc: 0.6799
Epoch 4/5
118948/118948 [==============================] - 22s 184us/step - loss: 0.5818 - acc: 0.6846
Epoch 5/5
118948/118948 [==============================] - 22s 183us/step - loss: 0.5747 - acc: 0.6914
[[[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]

 ...

 [[0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 1. 

('Num intersections in 30%: ', 33, '\n')
('Num in class0: ', 22224, '\n')
('Num in class1: ', 6434, '\n')
('File1: ', 'ENCFF322IFF_H3K27me3.bed', '\n')
('File2: ', 'ENCFF737AMS_H3K4me3.bed', '\n')
('Accuracy: ', 0.8919246574510905, '\n')
('Prob: ', array([[0.01746833],
       [0.1126452 ],
       [0.00795194],
       ...,
       [0.49136367],
       [0.17586266],
       [0.950077  ]], dtype=float32), '\n')
0.8919246574510905
23
(55885, 2)
(23991, 2)
('Shape is: ', (55885, 2))
[[[1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  ...
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]

 ...

 [[0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0.

Epoch 1/5
197926/197926 [==============================] - 39s 197us/step - loss: 0.5583 - acc: 0.6980
Epoch 2/5
197926/197926 [==============================] - 37s 189us/step - loss: 0.5222 - acc: 0.7219
Epoch 3/5
197926/197926 [==============================] - 37s 188us/step - loss: 0.5074 - acc: 0.7303
Epoch 4/5
197926/197926 [==============================] - 37s 187us/step - loss: 0.5003 - acc: 0.7354
Epoch 5/5
197926/197926 [==============================] - 37s 188us/step - loss: 0.4946 - acc: 0.7393
[[[0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  ...
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]
  ...
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]]

 ...

 [[0. 0. 1. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]]

 [[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  ...
  [1. 0. 

('Num intersections in 30%: ', 773, '\n')
('Num in class0: ', 59154, '\n')
('Num in class1: ', 30455, '\n')
('File1: ', 'ENCFF379CMJ_EP300.bed', '\n')
('File2: ', 'ENCFF578UBP_H3K27ac.bed', '\n')
('Accuracy: ', 0.8005745408553162, '\n')
('Prob: ', array([[0.28320956],
       [0.00910128],
       [0.42893413],
       ...,
       [0.5741073 ],
       [0.01177878],
       [0.14597832]], dtype=float32), '\n')
0.8005745408553162
1145
(168246, 2)
(88330, 2)
('Shape is: ', (168246, 2))
[[[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 0. 1.]
  [1. 0. 0. 0.]]

 [[0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]]

 [[0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 0. 1.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 ...

 [[0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 0. 1. 0.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [1. 0.

Epoch 1/5
144726/144726 [==============================] - 29s 198us/step - loss: 0.1980 - acc: 0.9258
Epoch 2/5
144726/144726 [==============================] - 27s 184us/step - loss: 0.1892 - acc: 0.9285
Epoch 3/5
144726/144726 [==============================] - 27s 186us/step - loss: 0.1850 - acc: 0.9309
Epoch 4/5
144726/144726 [==============================] - 28s 191us/step - loss: 0.1821 - acc: 0.9328
Epoch 5/5
144726/144726 [==============================] - 27s 189us/step - loss: 0.1788 - acc: 0.9347
[[[0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  ...
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]
  ...
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]]

 ...

 [[0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]
  ...
  [1. 0. 

('Num intersections in 30%: ', 33, '\n')
('Num in class0: ', 59154, '\n')
('Num in class1: ', 1767, '\n')
('File1: ', 'ENCFF379CMJ_EP300.bed', '\n')
('File2: ', 'ENCFF894VEM_H3K9me3.bed', '\n')
('Accuracy: ', 0.7478889236939202, '\n')
('Prob: ', array([[0.0129315 ],
       [0.00436694],
       [0.00384788],
       ...,
       [0.3518342 ],
       [0.05161775],
       [0.00957464]], dtype=float32), '\n')
0.7478889236939202
716
(129632, 2)
(58381, 2)
('Shape is: ', (129632, 2))
[[[0. 0. 1. 0.]
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]
  ...
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]]

 ...

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 0. 1.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0.

Epoch 1/5
132685/132685 [==============================] - 27s 206us/step - loss: 0.5827 - acc: 0.6797
Epoch 2/5
132685/132685 [==============================] - 25s 190us/step - loss: 0.5616 - acc: 0.6970
Epoch 3/5
132685/132685 [==============================] - 25s 189us/step - loss: 0.5545 - acc: 0.7036
Epoch 4/5
132685/132685 [==============================] - 25s 192us/step - loss: 0.5488 - acc: 0.7071
Epoch 5/5
132685/132685 [==============================] - 25s 187us/step - loss: 0.5428 - acc: 0.7131
[[[0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]]

 [[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 0. 1.]
  ...
  [0. 0. 0. 1.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 0. 1.]
  [1. 0. 0. 0.]
  [0. 0. 0. 1.]
  ...
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]

 ...

 [[0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 1. 

('Num intersections in 30%: ', 84, '\n')
('Num in class0: ', 27926, '\n')
('Num in class1: ', 6434, '\n')
('File1: ', 'ENCFF498CMP_H3K36me3.bed', '\n')
('File2: ', 'ENCFF737AMS_H3K4me3.bed', '\n')
('Accuracy: ', 0.9235754337515879, '\n')
('Prob: ', array([[0.01479936],
       [0.00692407],
       [0.01864046],
       ...,
       [0.96841943],
       [0.878531  ],
       [0.99994135]], dtype=float32), '\n')
0.9235754337515879
240
(68122, 2)
(29693, 2)
('Shape is: ', (68122, 2))
[[[0. 0. 1. 0.]
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]
  ...
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]]

 ...

 [[0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0

Epoch 1/5
98253/98253 [==============================] - 21s 214us/step - loss: 0.6655 - acc: 0.5847
Epoch 2/5
98253/98253 [==============================] - 19s 195us/step - loss: 0.6503 - acc: 0.6062
Epoch 3/5
98253/98253 [==============================] - 19s 194us/step - loss: 0.6432 - acc: 0.6147
Epoch 4/5
98253/98253 [==============================] - 19s 191us/step - loss: 0.6384 - acc: 0.6195
Epoch 5/5
98253/98253 [==============================] - 19s 194us/step - loss: 0.6338 - acc: 0.6251
[[[0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]]

 [[0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]]

 ...

 [[0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [

('Num intersections in 30%: ', 230, '\n')
('Num in class0: ', 30455, '\n')
('Num in class1: ', 6434, '\n')
('File1: ', 'ENCFF578UBP_H3K27ac.bed', '\n')
('File2: ', 'ENCFF737AMS_H3K4me3.bed', '\n')
('Accuracy: ', 0.8540127208582994, '\n')
('Prob: ', array([[0.02975874],
       [0.00955544],
       [0.04023985],
       ...,
       [0.33064857],
       [0.2971849 ],
       [0.41532597]], dtype=float32), '\n')
0.8540127208582994
42
(74787, 2)
(32222, 2)
('Shape is: ', (74787, 2))
[[[0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]
  ...
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 ...

 [[0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0.

Epoch 1/5
65969/65969 [==============================] - 15s 222us/step - loss: 0.2579 - acc: 0.9091
Epoch 2/5
65969/65969 [==============================] - 13s 199us/step - loss: 0.2463 - acc: 0.9119
Epoch 3/5
65969/65969 [==============================] - 13s 194us/step - loss: 0.2422 - acc: 0.9130
Epoch 4/5
65969/65969 [==============================] - 13s 192us/step - loss: 0.2392 - acc: 0.9134
Epoch 5/5
65969/65969 [==============================] - 13s 196us/step - loss: 0.2360 - acc: 0.9138
[[[0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  ...
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]
  ...
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]
  ...
  [0. 0. 0. 1.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 ...

 [[0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]
  ...
  [1. 0. 0. 0.]
  [

('Num intersections in 30%: ', 47, '\n')
('Num in class0: ', 29176, '\n')
('Num in class1: ', 1767, '\n')
('File1: ', 'ENCFF624XRN_H2AFZ.bed', '\n')
('File2: ', 'ENCFF894VEM_H3K9me3.bed', '\n')
('Accuracy: ', 0.7534633496471039, '\n')
('Prob: ', array([[0.13690075],
       [0.0461924 ],
       [0.00820078],
       ...,
       [0.98853976],
       [0.629535  ],
       [0.02698821]], dtype=float32), '\n')
0.7534633496471039
3
(19117, 2)
(8201, 2)
('Shape is: ', (19117, 2))
[[[0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]

 [[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]]

 [[0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]

 ...

 [[0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]]

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

<Figure size 504x504 with 0 Axes>

In [7]:
print df_final

                       File1                     File2  Accuracy
0    ENCFF127XXD_H3K4me3.bed   ENCFF099LMD_H3K4me2.bed   0.64166
1    ENCFF127XXD_H3K4me3.bed  ENCFF139CKE_H4K20me1.bed  0.767099
2    ENCFF127XXD_H3K4me3.bed   ENCFF183UQD_H3K4me1.bed  0.761397
3    ENCFF127XXD_H3K4me3.bed  ENCFF322IFF_H3K27me3.bed  0.778297
4    ENCFF127XXD_H3K4me3.bed     ENCFF379CMJ_EP300.bed   0.74504
5    ENCFF127XXD_H3K4me3.bed  ENCFF498CMP_H3K36me3.bed  0.780132
6    ENCFF127XXD_H3K4me3.bed   ENCFF578UBP_H3K27ac.bed  0.755473
7    ENCFF127XXD_H3K4me3.bed     ENCFF624XRN_H2AFZ.bed  0.605159
8    ENCFF127XXD_H3K4me3.bed   ENCFF737AMS_H3K4me3.bed  0.751251
9    ENCFF127XXD_H3K4me3.bed   ENCFF894VEM_H3K9me3.bed  0.808993
10   ENCFF099LMD_H3K4me2.bed  ENCFF139CKE_H4K20me1.bed  0.687803
11   ENCFF099LMD_H3K4me2.bed   ENCFF183UQD_H3K4me1.bed  0.689985
12   ENCFF099LMD_H3K4me2.bed  ENCFF322IFF_H3K27me3.bed   0.65814
13   ENCFF099LMD_H3K4me2.bed     ENCFF379CMJ_EP300.bed  0.768581
14   ENCFF099LMD_H3K4me2.

In [8]:
df_final.to_csv("FinalAccuracies_withmodel.csv")


In [9]:
print df_final


                       File1                     File2  Accuracy
0    ENCFF127XXD_H3K4me3.bed   ENCFF099LMD_H3K4me2.bed   0.64166
1    ENCFF127XXD_H3K4me3.bed  ENCFF139CKE_H4K20me1.bed  0.767099
2    ENCFF127XXD_H3K4me3.bed   ENCFF183UQD_H3K4me1.bed  0.761397
3    ENCFF127XXD_H3K4me3.bed  ENCFF322IFF_H3K27me3.bed  0.778297
4    ENCFF127XXD_H3K4me3.bed     ENCFF379CMJ_EP300.bed   0.74504
5    ENCFF127XXD_H3K4me3.bed  ENCFF498CMP_H3K36me3.bed  0.780132
6    ENCFF127XXD_H3K4me3.bed   ENCFF578UBP_H3K27ac.bed  0.755473
7    ENCFF127XXD_H3K4me3.bed     ENCFF624XRN_H2AFZ.bed  0.605159
8    ENCFF127XXD_H3K4me3.bed   ENCFF737AMS_H3K4me3.bed  0.751251
9    ENCFF127XXD_H3K4me3.bed   ENCFF894VEM_H3K9me3.bed  0.808993
10   ENCFF099LMD_H3K4me2.bed  ENCFF139CKE_H4K20me1.bed  0.687803
11   ENCFF099LMD_H3K4me2.bed   ENCFF183UQD_H3K4me1.bed  0.689985
12   ENCFF099LMD_H3K4me2.bed  ENCFF322IFF_H3K27me3.bed   0.65814
13   ENCFF099LMD_H3K4me2.bed     ENCFF379CMJ_EP300.bed  0.768581
14   ENCFF099LMD_H3K4me2.